### ISSUE TITLE
How can an aggregation be reactive?

### ISSUE THREAD

**Issue by 0o-de-lally** [mikowals/find-async#3]
Would be great to have serverside aggregation events that respond to a collection or document being updated.
Is this possible with this package? If not, what has to be done to make it possible?

**Comment by mikowals** [comment]
Yeah, that would be great.  This package is not reactive and making it reactive for all aggregation use cases would be a massive undertaking.  

If you have a particular use case I would just begin by building a solution for that.  This could be done either by nesting meteor observes or by using an aggregation package like this and polling the db.  

You could also ask at [the forum](https://forums.meteor.com/) to see if anyone else has worked on this.

**Comment by 0o-de-lally** [comment]
I get that it's out of scope. Anyone tried to use https://atmospherejs.com/peerlibrary/peerdb with meteor aggregates?
